/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/api/health": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Health check */
    get: operations["getHealth"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/config": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get merged config with layers */
    get: operations["getConfig"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/config/setting": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Update a config setting */
    post: operations["updateConfigSetting"];
    /** Delete a config setting */
    delete: operations["deleteConfigSetting"];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/config/setting/move": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Move a config setting up or down */
    post: operations["moveConfigSetting"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/agents": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List agents */
    get: operations["getAgents"];
    put?: never;
    /** Create an agent */
    post: operations["createAgent"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/agents/{name}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get agent detail */
    get: operations["getAgent"];
    /** Update an agent */
    put: operations["updateAgent"];
    post?: never;
    /** Delete an agent */
    delete: operations["deleteAgent"];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/commands": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List commands */
    get: operations["getCommands"];
    put?: never;
    /** Create a command */
    post: operations["createCommand"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/commands/{scope}/{folder}/{name}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get command detail */
    get: operations["getCommand"];
    /** Update a command */
    put: operations["updateCommand"];
    post?: never;
    /** Delete a command */
    delete: operations["deleteCommand"];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/skills": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List skills */
    get: operations["getSkills"];
    put?: never;
    /** Create a skill */
    post: operations["createSkill"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/skills/{scope}/{name}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get skill detail */
    get: operations["getSkill"];
    /** Update a skill */
    put: operations["updateSkill"];
    post?: never;
    /** Delete a skill */
    delete: operations["deleteSkill"];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/hooks": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List hooks */
    get: operations["getHooks"];
    put?: never;
    /** Create a hook */
    post: operations["createHook"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/hooks/{id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    /** Update a hook */
    put: operations["updateHook"];
    post?: never;
    /** Delete a hook */
    delete: operations["deleteHook"];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/backups": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List backups */
    get: operations["getBackups"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/backups/{id}/restore": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Restore a backup */
    post: operations["restoreBackup"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/projects": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List projects */
    get: operations["getProjects"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/plugins": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List plugins */
    get: operations["getPlugins"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/features": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get features data */
    get: operations["getFeatures"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/features/{key}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    /** Update a feature value */
    put: operations["updateFeature"];
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/search": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Search across all resources */
    get: operations["search"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/watch": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** SSE file watcher stream */
    get: operations["watch"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/auth/login": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Login with password */
    post: operations["login"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/auth/logout": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Logout */
    post: operations["logout"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    HealthResponse: {
      status: string;
    } & {
      [key: string]: unknown;
    };
    SuccessResponse: {
      success: boolean;
    } & {
      [key: string]: unknown;
    };
    ConfigLayer: {
      /** @enum {string} */
      source: "global" | "global-local" | "project" | "project-local";
      filePath: string;
      exists: boolean;
      content?: {
        [key: string]: unknown;
      } | null;
    } & {
      [key: string]: unknown;
    };
    ConfigResponse: {
      merged: {
        [key: string]: unknown;
      };
      layers: components["schemas"]["ConfigLayer"][];
    } & {
      [key: string]: unknown;
    };
    UpdateConfigSettingRequest: {
      keyPath: string[];
      value: unknown;
    } & {
      [key: string]: unknown;
    };
    DeleteConfigSettingRequest: {
      keyPath: string[];
    } & {
      [key: string]: unknown;
    };
    MoveConfigSettingRequest: {
      keyPath: string[];
      /** @enum {string} */
      direction: "up" | "down";
    } & {
      [key: string]: unknown;
    };
    AgentFile: {
      name: string;
      description: string;
      fileName: string;
      filePath: string;
      tools?: string;
      color?: string;
      bodyPreview: string;
      isEditable: boolean;
    } & {
      [key: string]: unknown;
    };
    AgentDetail: {
      name: string;
      description: string;
      fileName: string;
      filePath: string;
      tools?: string;
      color?: string;
      body: string;
      isEditable: boolean;
    } & {
      [key: string]: unknown;
    };
    CreateAgentRequest: {
      name: string;
      description?: string;
      tools?: string;
      color?: string;
      body: string;
      /** @enum {string} */
      scope: "global" | "project";
      projectPath?: string;
    } & {
      [key: string]: unknown;
    };
    UpdateAgentRequest: {
      description?: string;
      tools?: string;
      color?: string;
      body: string;
      /** @enum {string} */
      scope: "global" | "project";
      projectPath?: string;
    } & {
      [key: string]: unknown;
    };
    DeleteAgentRequest: {
      /** @enum {string} */
      scope: "global" | "project";
      projectPath?: string;
    } & {
      [key: string]: unknown;
    };
    CommandFile: {
      name: string;
      fileName: string;
      filePath: string;
      folder: string;
      bodyPreview: string;
      isEditable: boolean;
    } & {
      [key: string]: unknown;
    };
    CommandDetail: {
      name: string;
      fileName: string;
      filePath: string;
      folder: string;
      body: string;
      isEditable: boolean;
    } & {
      [key: string]: unknown;
    };
    CreateCommandRequest: {
      name: string;
      folder: string;
      body: string;
      /** @enum {string} */
      scope: "global" | "project";
      projectPath?: string;
    } & {
      [key: string]: unknown;
    };
    UpdateCommandRequest: {
      body: string;
      projectPath?: string;
    } & {
      [key: string]: unknown;
    };
    SkillFile: {
      name: string;
      description: string;
      folderName: string;
      filePath: string;
      bodyPreview: string;
      isEditable: boolean;
    } & {
      [key: string]: unknown;
    };
    SkillDetail: {
      name: string;
      description: string;
      folderName: string;
      filePath: string;
      body: string;
      isEditable: boolean;
    } & {
      [key: string]: unknown;
    };
    CreateSkillRequest: {
      name: string;
      description?: string;
      body: string;
      /** @enum {string} */
      scope: "global" | "project";
      projectPath?: string;
    } & {
      [key: string]: unknown;
    };
    UpdateSkillRequest: {
      description?: string;
      body: string;
      projectPath?: string;
    } & {
      [key: string]: unknown;
    };
    HookCommand: {
      /** @enum {string} */
      type: "command";
      command: string;
    } & {
      [key: string]: unknown;
    };
    HookDefinition: {
      hooks: components["schemas"]["HookCommand"][];
      matcher?: string;
    } & {
      [key: string]: unknown;
    };
    HooksByEvent: {
      SessionStart?: components["schemas"]["HookDefinition"][];
      UserPromptSubmit?: components["schemas"]["HookDefinition"][];
      PreToolUse?: components["schemas"]["HookDefinition"][];
      PostToolUse?: components["schemas"]["HookDefinition"][];
      Notification?: components["schemas"]["HookDefinition"][];
      Stop?: components["schemas"]["HookDefinition"][];
      SubagentStop?: components["schemas"]["HookDefinition"][];
    } & {
      [key: string]: unknown;
    };
    HookScope: {
      hooks?: components["schemas"]["HooksByEvent"];
    } & {
      [key: string]: unknown;
    };
    HooksResponse: {
      global?: components["schemas"]["HookScope"];
      project?: components["schemas"]["HookScope"];
    } & {
      [key: string]: unknown;
    };
    CreateHookRequest: {
      event: string;
      matcher?: string;
      commands: string[];
      /** @enum {string} */
      scope: "global" | "project";
      projectPath?: string;
    } & {
      [key: string]: unknown;
    };
    UpdateHookRequest: {
      event: string;
      matcher?: string;
      commands: string[];
      /** @enum {string} */
      scope: "global" | "project";
      projectPath?: string;
    } & {
      [key: string]: unknown;
    };
    BackupFile: {
      id: string;
      filePath: string;
      originalPath: string;
      createdAt: string;
      /** Format: int64 */
      size: number;
    } & {
      [key: string]: unknown;
    };
    ProjectFile: {
      name: string;
      path: string;
    } & {
      [key: string]: unknown;
    };
    PluginFile: {
      name: string;
      path: string;
      isUserOwned: boolean;
    } & {
      [key: string]: unknown;
    };
    FeatureDefinition: {
      key: string;
      name: string;
      description: string;
      /** @enum {string} */
      type: "env" | "setting";
      category: string;
      values?: string[];
    } & {
      [key: string]: unknown;
    };
    Feature: {
      definition: components["schemas"]["FeatureDefinition"];
      currentValue?: unknown;
      isDocumented: boolean;
    } & {
      [key: string]: unknown;
    };
    FeaturesData: {
      version?: string | null;
      features: components["schemas"]["Feature"][];
      totalDiscovered: number;
      totalDocumented: number;
    } & {
      [key: string]: unknown;
    };
    UpdateFeatureRequest: {
      value: unknown;
      /** @enum {string} */
      type: "env" | "setting";
    } & {
      [key: string]: unknown;
    };
    SearchResult: {
      /** @enum {string} */
      type: "agent" | "command" | "skill" | "hook";
      name: string;
      description?: string;
      filePath: string;
      preview: string;
    } & {
      [key: string]: unknown;
    };
    LoginRequest: {
      password: string;
    } & {
      [key: string]: unknown;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  getHealth: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HealthResponse"];
        };
      };
    };
  };
  getConfig: {
    parameters: {
      query?: {
        projectPath?: string;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ConfigResponse"];
        };
      };
    };
  };
  updateConfigSetting: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["UpdateConfigSettingRequest"];
      };
    };
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["SuccessResponse"];
        };
      };
    };
  };
  deleteConfigSetting: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["DeleteConfigSettingRequest"];
      };
    };
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["SuccessResponse"];
        };
      };
    };
  };
  moveConfigSetting: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["MoveConfigSettingRequest"];
      };
    };
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["SuccessResponse"];
        };
      };
    };
  };
  getAgents: {
    parameters: {
      query?: {
        scope?: "global" | "project";
        projectPath?: string;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["AgentFile"][];
        };
      };
    };
  };
  createAgent: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["CreateAgentRequest"];
      };
    };
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["AgentFile"];
        };
      };
    };
  };
  getAgent: {
    parameters: {
      query?: {
        scope?: string;
        projectPath?: string;
      };
      header?: never;
      path: {
        name: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["AgentDetail"];
        };
      };
    };
  };
  updateAgent: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        name: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["UpdateAgentRequest"];
      };
    };
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["AgentDetail"];
        };
      };
    };
  };
  deleteAgent: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        name: string;
      };
      cookie?: never;
    };
    requestBody?: {
      content: {
        "application/json": components["schemas"]["DeleteAgentRequest"];
      };
    };
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["SuccessResponse"];
        };
      };
    };
  };
  getCommands: {
    parameters: {
      query?: {
        scope?: "global" | "project";
        projectPath?: string;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["CommandFile"][];
        };
      };
    };
  };
  createCommand: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["CreateCommandRequest"];
      };
    };
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["CommandFile"];
        };
      };
    };
  };
  getCommand: {
    parameters: {
      query?: {
        projectPath?: string;
      };
      header?: never;
      path: {
        scope: string;
        folder: string;
        name: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["CommandDetail"];
        };
      };
    };
  };
  updateCommand: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        scope: string;
        folder: string;
        name: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["UpdateCommandRequest"];
      };
    };
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["CommandDetail"];
        };
      };
    };
  };
  deleteCommand: {
    parameters: {
      query?: {
        projectPath?: string;
      };
      header?: never;
      path: {
        scope: string;
        folder: string;
        name: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["SuccessResponse"];
        };
      };
    };
  };
  getSkills: {
    parameters: {
      query?: {
        scope?: "global" | "project";
        projectPath?: string;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["SkillFile"][];
        };
      };
    };
  };
  createSkill: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["CreateSkillRequest"];
      };
    };
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["SkillFile"];
        };
      };
    };
  };
  getSkill: {
    parameters: {
      query?: {
        projectPath?: string;
      };
      header?: never;
      path: {
        scope: string;
        name: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["SkillDetail"];
        };
      };
    };
  };
  updateSkill: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        scope: string;
        name: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["UpdateSkillRequest"];
      };
    };
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["SkillDetail"];
        };
      };
    };
  };
  deleteSkill: {
    parameters: {
      query?: {
        projectPath?: string;
      };
      header?: never;
      path: {
        scope: string;
        name: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["SuccessResponse"];
        };
      };
    };
  };
  getHooks: {
    parameters: {
      query?: {
        projectPath?: string;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HooksResponse"];
        };
      };
    };
  };
  createHook: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["CreateHookRequest"];
      };
    };
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["SuccessResponse"];
        };
      };
    };
  };
  updateHook: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["UpdateHookRequest"];
      };
    };
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["SuccessResponse"];
        };
      };
    };
  };
  deleteHook: {
    parameters: {
      query?: {
        scope?: string;
        projectPath?: string;
      };
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["SuccessResponse"];
        };
      };
    };
  };
  getBackups: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["BackupFile"][];
        };
      };
    };
  };
  restoreBackup: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["SuccessResponse"];
        };
      };
    };
  };
  getProjects: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ProjectFile"][];
        };
      };
    };
  };
  getPlugins: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["PluginFile"][];
        };
      };
    };
  };
  getFeatures: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["FeaturesData"];
        };
      };
    };
  };
  updateFeature: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        key: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["UpdateFeatureRequest"];
      };
    };
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["SuccessResponse"];
        };
      };
    };
  };
  search: {
    parameters: {
      query: {
        q: string;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["SearchResult"][];
        };
      };
    };
  };
  watch: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description SSE stream */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "text/event-stream": string;
        };
      };
    };
  };
  login: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["LoginRequest"];
      };
    };
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["SuccessResponse"];
        };
      };
    };
  };
  logout: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["SuccessResponse"];
        };
      };
    };
  };
}
