/// <reference types="vitest/config" />

import { fileURLToPath, URL } from "node:url";
import viteReact from "@vitejs/plugin-react";
import { defineConfig } from "vitest/config";

export default defineConfig({
  resolve: {
    alias: {
      "@": fileURLToPath(new URL("./src", import.meta.url)),
    },
  },
  plugins: [viteReact()],
  test: {
    globals: true,
    environment: "node",
    include: ["src/**/*.test.{ts,tsx}"],
    coverage: {
      provider: "v8",
      // include constrains the file set, so custom exclude does not need to repeat
      // Vitest's default exclusions (node_modules, dist, etc.)
      include: ["src/**/*.{ts,tsx}"],
      exclude: [
        "src/**/*.test.{ts,tsx}",
        "src/lib/api-types.ts",
        "src/routeTree.gen.ts", // generated by TanStack Router — excluded to avoid skewing coverage
      ],
      thresholds: {
        lines: 20,
        statements: 20,
        functions: 20,
        branches: 15,
      },
    },
  },
});
