/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SetupRouteImport } from './routes/setup'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProjectsIndexRouteImport } from './routes/projects/index'
import { Route as GlobalIndexRouteImport } from './routes/global/index'
import { Route as GlobalSettingsRouteImport } from './routes/global/settings'
import { Route as GlobalPluginsRouteImport } from './routes/global/plugins'
import { Route as GlobalHooksRouteImport } from './routes/global/hooks'
import { Route as ProjectsProjectIdRouteRouteImport } from './routes/projects/$projectId/route'
import { Route as GlobalSkillsRouteRouteImport } from './routes/global/skills/route'
import { Route as GlobalCommandsRouteRouteImport } from './routes/global/commands/route'
import { Route as GlobalAgentsRouteRouteImport } from './routes/global/agents/route'
import { Route as ProjectsProjectIdIndexRouteImport } from './routes/projects/$projectId/index'
import { Route as GlobalSkillsIndexRouteImport } from './routes/global/skills/index'
import { Route as GlobalCommandsIndexRouteImport } from './routes/global/commands/index'
import { Route as GlobalAgentsIndexRouteImport } from './routes/global/agents/index'
import { Route as ProjectsProjectIdSettingsRouteImport } from './routes/projects/$projectId/settings'
import { Route as GlobalSkillsSkillNameRouteImport } from './routes/global/skills/$skillName'
import { Route as GlobalAgentsAgentNameRouteImport } from './routes/global/agents/$agentName'
import { Route as ProjectsProjectIdSkillsRouteRouteImport } from './routes/projects/$projectId/skills/route'
import { Route as ProjectsProjectIdCommandsRouteRouteImport } from './routes/projects/$projectId/commands/route'
import { Route as ProjectsProjectIdAgentsRouteRouteImport } from './routes/projects/$projectId/agents/route'
import { Route as ProjectsProjectIdSkillsIndexRouteImport } from './routes/projects/$projectId/skills/index'
import { Route as ProjectsProjectIdCommandsIndexRouteImport } from './routes/projects/$projectId/commands/index'
import { Route as ProjectsProjectIdAgentsIndexRouteImport } from './routes/projects/$projectId/agents/index'
import { Route as ProjectsProjectIdSkillsSkillNameRouteImport } from './routes/projects/$projectId/skills/$skillName'
import { Route as ProjectsProjectIdAgentsAgentNameRouteImport } from './routes/projects/$projectId/agents/$agentName'
import { Route as GlobalCommandsFolderCommandNameRouteImport } from './routes/global/commands/$folder.$commandName'
import { Route as ProjectsProjectIdCommandsFolderCommandNameRouteImport } from './routes/projects/$projectId/commands/$folder.$commandName'

const SetupRoute = SetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsIndexRoute = ProjectsIndexRouteImport.update({
  id: '/projects/',
  path: '/projects/',
  getParentRoute: () => rootRouteImport,
} as any)
const GlobalIndexRoute = GlobalIndexRouteImport.update({
  id: '/global/',
  path: '/global/',
  getParentRoute: () => rootRouteImport,
} as any)
const GlobalSettingsRoute = GlobalSettingsRouteImport.update({
  id: '/global/settings',
  path: '/global/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const GlobalPluginsRoute = GlobalPluginsRouteImport.update({
  id: '/global/plugins',
  path: '/global/plugins',
  getParentRoute: () => rootRouteImport,
} as any)
const GlobalHooksRoute = GlobalHooksRouteImport.update({
  id: '/global/hooks',
  path: '/global/hooks',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsProjectIdRouteRoute = ProjectsProjectIdRouteRouteImport.update({
  id: '/projects/$projectId',
  path: '/projects/$projectId',
  getParentRoute: () => rootRouteImport,
} as any)
const GlobalSkillsRouteRoute = GlobalSkillsRouteRouteImport.update({
  id: '/global/skills',
  path: '/global/skills',
  getParentRoute: () => rootRouteImport,
} as any)
const GlobalCommandsRouteRoute = GlobalCommandsRouteRouteImport.update({
  id: '/global/commands',
  path: '/global/commands',
  getParentRoute: () => rootRouteImport,
} as any)
const GlobalAgentsRouteRoute = GlobalAgentsRouteRouteImport.update({
  id: '/global/agents',
  path: '/global/agents',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsProjectIdIndexRoute = ProjectsProjectIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProjectsProjectIdRouteRoute,
} as any)
const GlobalSkillsIndexRoute = GlobalSkillsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => GlobalSkillsRouteRoute,
} as any)
const GlobalCommandsIndexRoute = GlobalCommandsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => GlobalCommandsRouteRoute,
} as any)
const GlobalAgentsIndexRoute = GlobalAgentsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => GlobalAgentsRouteRoute,
} as any)
const ProjectsProjectIdSettingsRoute =
  ProjectsProjectIdSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => ProjectsProjectIdRouteRoute,
  } as any)
const GlobalSkillsSkillNameRoute = GlobalSkillsSkillNameRouteImport.update({
  id: '/$skillName',
  path: '/$skillName',
  getParentRoute: () => GlobalSkillsRouteRoute,
} as any)
const GlobalAgentsAgentNameRoute = GlobalAgentsAgentNameRouteImport.update({
  id: '/$agentName',
  path: '/$agentName',
  getParentRoute: () => GlobalAgentsRouteRoute,
} as any)
const ProjectsProjectIdSkillsRouteRoute =
  ProjectsProjectIdSkillsRouteRouteImport.update({
    id: '/skills',
    path: '/skills',
    getParentRoute: () => ProjectsProjectIdRouteRoute,
  } as any)
const ProjectsProjectIdCommandsRouteRoute =
  ProjectsProjectIdCommandsRouteRouteImport.update({
    id: '/commands',
    path: '/commands',
    getParentRoute: () => ProjectsProjectIdRouteRoute,
  } as any)
const ProjectsProjectIdAgentsRouteRoute =
  ProjectsProjectIdAgentsRouteRouteImport.update({
    id: '/agents',
    path: '/agents',
    getParentRoute: () => ProjectsProjectIdRouteRoute,
  } as any)
const ProjectsProjectIdSkillsIndexRoute =
  ProjectsProjectIdSkillsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => ProjectsProjectIdSkillsRouteRoute,
  } as any)
const ProjectsProjectIdCommandsIndexRoute =
  ProjectsProjectIdCommandsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => ProjectsProjectIdCommandsRouteRoute,
  } as any)
const ProjectsProjectIdAgentsIndexRoute =
  ProjectsProjectIdAgentsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => ProjectsProjectIdAgentsRouteRoute,
  } as any)
const ProjectsProjectIdSkillsSkillNameRoute =
  ProjectsProjectIdSkillsSkillNameRouteImport.update({
    id: '/$skillName',
    path: '/$skillName',
    getParentRoute: () => ProjectsProjectIdSkillsRouteRoute,
  } as any)
const ProjectsProjectIdAgentsAgentNameRoute =
  ProjectsProjectIdAgentsAgentNameRouteImport.update({
    id: '/$agentName',
    path: '/$agentName',
    getParentRoute: () => ProjectsProjectIdAgentsRouteRoute,
  } as any)
const GlobalCommandsFolderCommandNameRoute =
  GlobalCommandsFolderCommandNameRouteImport.update({
    id: '/$folder/$commandName',
    path: '/$folder/$commandName',
    getParentRoute: () => GlobalCommandsRouteRoute,
  } as any)
const ProjectsProjectIdCommandsFolderCommandNameRoute =
  ProjectsProjectIdCommandsFolderCommandNameRouteImport.update({
    id: '/$folder/$commandName',
    path: '/$folder/$commandName',
    getParentRoute: () => ProjectsProjectIdCommandsRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/setup': typeof SetupRoute
  '/global/agents': typeof GlobalAgentsRouteRouteWithChildren
  '/global/commands': typeof GlobalCommandsRouteRouteWithChildren
  '/global/skills': typeof GlobalSkillsRouteRouteWithChildren
  '/projects/$projectId': typeof ProjectsProjectIdRouteRouteWithChildren
  '/global/hooks': typeof GlobalHooksRoute
  '/global/plugins': typeof GlobalPluginsRoute
  '/global/settings': typeof GlobalSettingsRoute
  '/global/': typeof GlobalIndexRoute
  '/projects/': typeof ProjectsIndexRoute
  '/projects/$projectId/agents': typeof ProjectsProjectIdAgentsRouteRouteWithChildren
  '/projects/$projectId/commands': typeof ProjectsProjectIdCommandsRouteRouteWithChildren
  '/projects/$projectId/skills': typeof ProjectsProjectIdSkillsRouteRouteWithChildren
  '/global/agents/$agentName': typeof GlobalAgentsAgentNameRoute
  '/global/skills/$skillName': typeof GlobalSkillsSkillNameRoute
  '/projects/$projectId/settings': typeof ProjectsProjectIdSettingsRoute
  '/global/agents/': typeof GlobalAgentsIndexRoute
  '/global/commands/': typeof GlobalCommandsIndexRoute
  '/global/skills/': typeof GlobalSkillsIndexRoute
  '/projects/$projectId/': typeof ProjectsProjectIdIndexRoute
  '/global/commands/$folder/$commandName': typeof GlobalCommandsFolderCommandNameRoute
  '/projects/$projectId/agents/$agentName': typeof ProjectsProjectIdAgentsAgentNameRoute
  '/projects/$projectId/skills/$skillName': typeof ProjectsProjectIdSkillsSkillNameRoute
  '/projects/$projectId/agents/': typeof ProjectsProjectIdAgentsIndexRoute
  '/projects/$projectId/commands/': typeof ProjectsProjectIdCommandsIndexRoute
  '/projects/$projectId/skills/': typeof ProjectsProjectIdSkillsIndexRoute
  '/projects/$projectId/commands/$folder/$commandName': typeof ProjectsProjectIdCommandsFolderCommandNameRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/setup': typeof SetupRoute
  '/global/hooks': typeof GlobalHooksRoute
  '/global/plugins': typeof GlobalPluginsRoute
  '/global/settings': typeof GlobalSettingsRoute
  '/global': typeof GlobalIndexRoute
  '/projects': typeof ProjectsIndexRoute
  '/global/agents/$agentName': typeof GlobalAgentsAgentNameRoute
  '/global/skills/$skillName': typeof GlobalSkillsSkillNameRoute
  '/projects/$projectId/settings': typeof ProjectsProjectIdSettingsRoute
  '/global/agents': typeof GlobalAgentsIndexRoute
  '/global/commands': typeof GlobalCommandsIndexRoute
  '/global/skills': typeof GlobalSkillsIndexRoute
  '/projects/$projectId': typeof ProjectsProjectIdIndexRoute
  '/global/commands/$folder/$commandName': typeof GlobalCommandsFolderCommandNameRoute
  '/projects/$projectId/agents/$agentName': typeof ProjectsProjectIdAgentsAgentNameRoute
  '/projects/$projectId/skills/$skillName': typeof ProjectsProjectIdSkillsSkillNameRoute
  '/projects/$projectId/agents': typeof ProjectsProjectIdAgentsIndexRoute
  '/projects/$projectId/commands': typeof ProjectsProjectIdCommandsIndexRoute
  '/projects/$projectId/skills': typeof ProjectsProjectIdSkillsIndexRoute
  '/projects/$projectId/commands/$folder/$commandName': typeof ProjectsProjectIdCommandsFolderCommandNameRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/setup': typeof SetupRoute
  '/global/agents': typeof GlobalAgentsRouteRouteWithChildren
  '/global/commands': typeof GlobalCommandsRouteRouteWithChildren
  '/global/skills': typeof GlobalSkillsRouteRouteWithChildren
  '/projects/$projectId': typeof ProjectsProjectIdRouteRouteWithChildren
  '/global/hooks': typeof GlobalHooksRoute
  '/global/plugins': typeof GlobalPluginsRoute
  '/global/settings': typeof GlobalSettingsRoute
  '/global/': typeof GlobalIndexRoute
  '/projects/': typeof ProjectsIndexRoute
  '/projects/$projectId/agents': typeof ProjectsProjectIdAgentsRouteRouteWithChildren
  '/projects/$projectId/commands': typeof ProjectsProjectIdCommandsRouteRouteWithChildren
  '/projects/$projectId/skills': typeof ProjectsProjectIdSkillsRouteRouteWithChildren
  '/global/agents/$agentName': typeof GlobalAgentsAgentNameRoute
  '/global/skills/$skillName': typeof GlobalSkillsSkillNameRoute
  '/projects/$projectId/settings': typeof ProjectsProjectIdSettingsRoute
  '/global/agents/': typeof GlobalAgentsIndexRoute
  '/global/commands/': typeof GlobalCommandsIndexRoute
  '/global/skills/': typeof GlobalSkillsIndexRoute
  '/projects/$projectId/': typeof ProjectsProjectIdIndexRoute
  '/global/commands/$folder/$commandName': typeof GlobalCommandsFolderCommandNameRoute
  '/projects/$projectId/agents/$agentName': typeof ProjectsProjectIdAgentsAgentNameRoute
  '/projects/$projectId/skills/$skillName': typeof ProjectsProjectIdSkillsSkillNameRoute
  '/projects/$projectId/agents/': typeof ProjectsProjectIdAgentsIndexRoute
  '/projects/$projectId/commands/': typeof ProjectsProjectIdCommandsIndexRoute
  '/projects/$projectId/skills/': typeof ProjectsProjectIdSkillsIndexRoute
  '/projects/$projectId/commands/$folder/$commandName': typeof ProjectsProjectIdCommandsFolderCommandNameRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/setup'
    | '/global/agents'
    | '/global/commands'
    | '/global/skills'
    | '/projects/$projectId'
    | '/global/hooks'
    | '/global/plugins'
    | '/global/settings'
    | '/global/'
    | '/projects/'
    | '/projects/$projectId/agents'
    | '/projects/$projectId/commands'
    | '/projects/$projectId/skills'
    | '/global/agents/$agentName'
    | '/global/skills/$skillName'
    | '/projects/$projectId/settings'
    | '/global/agents/'
    | '/global/commands/'
    | '/global/skills/'
    | '/projects/$projectId/'
    | '/global/commands/$folder/$commandName'
    | '/projects/$projectId/agents/$agentName'
    | '/projects/$projectId/skills/$skillName'
    | '/projects/$projectId/agents/'
    | '/projects/$projectId/commands/'
    | '/projects/$projectId/skills/'
    | '/projects/$projectId/commands/$folder/$commandName'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/setup'
    | '/global/hooks'
    | '/global/plugins'
    | '/global/settings'
    | '/global'
    | '/projects'
    | '/global/agents/$agentName'
    | '/global/skills/$skillName'
    | '/projects/$projectId/settings'
    | '/global/agents'
    | '/global/commands'
    | '/global/skills'
    | '/projects/$projectId'
    | '/global/commands/$folder/$commandName'
    | '/projects/$projectId/agents/$agentName'
    | '/projects/$projectId/skills/$skillName'
    | '/projects/$projectId/agents'
    | '/projects/$projectId/commands'
    | '/projects/$projectId/skills'
    | '/projects/$projectId/commands/$folder/$commandName'
  id:
    | '__root__'
    | '/'
    | '/setup'
    | '/global/agents'
    | '/global/commands'
    | '/global/skills'
    | '/projects/$projectId'
    | '/global/hooks'
    | '/global/plugins'
    | '/global/settings'
    | '/global/'
    | '/projects/'
    | '/projects/$projectId/agents'
    | '/projects/$projectId/commands'
    | '/projects/$projectId/skills'
    | '/global/agents/$agentName'
    | '/global/skills/$skillName'
    | '/projects/$projectId/settings'
    | '/global/agents/'
    | '/global/commands/'
    | '/global/skills/'
    | '/projects/$projectId/'
    | '/global/commands/$folder/$commandName'
    | '/projects/$projectId/agents/$agentName'
    | '/projects/$projectId/skills/$skillName'
    | '/projects/$projectId/agents/'
    | '/projects/$projectId/commands/'
    | '/projects/$projectId/skills/'
    | '/projects/$projectId/commands/$folder/$commandName'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SetupRoute: typeof SetupRoute
  GlobalAgentsRouteRoute: typeof GlobalAgentsRouteRouteWithChildren
  GlobalCommandsRouteRoute: typeof GlobalCommandsRouteRouteWithChildren
  GlobalSkillsRouteRoute: typeof GlobalSkillsRouteRouteWithChildren
  ProjectsProjectIdRouteRoute: typeof ProjectsProjectIdRouteRouteWithChildren
  GlobalHooksRoute: typeof GlobalHooksRoute
  GlobalPluginsRoute: typeof GlobalPluginsRoute
  GlobalSettingsRoute: typeof GlobalSettingsRoute
  GlobalIndexRoute: typeof GlobalIndexRoute
  ProjectsIndexRoute: typeof ProjectsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/setup': {
      id: '/setup'
      path: '/setup'
      fullPath: '/setup'
      preLoaderRoute: typeof SetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/': {
      id: '/projects/'
      path: '/projects'
      fullPath: '/projects/'
      preLoaderRoute: typeof ProjectsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/global/': {
      id: '/global/'
      path: '/global'
      fullPath: '/global/'
      preLoaderRoute: typeof GlobalIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/global/settings': {
      id: '/global/settings'
      path: '/global/settings'
      fullPath: '/global/settings'
      preLoaderRoute: typeof GlobalSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/global/plugins': {
      id: '/global/plugins'
      path: '/global/plugins'
      fullPath: '/global/plugins'
      preLoaderRoute: typeof GlobalPluginsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/global/hooks': {
      id: '/global/hooks'
      path: '/global/hooks'
      fullPath: '/global/hooks'
      preLoaderRoute: typeof GlobalHooksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/$projectId': {
      id: '/projects/$projectId'
      path: '/projects/$projectId'
      fullPath: '/projects/$projectId'
      preLoaderRoute: typeof ProjectsProjectIdRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/global/skills': {
      id: '/global/skills'
      path: '/global/skills'
      fullPath: '/global/skills'
      preLoaderRoute: typeof GlobalSkillsRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/global/commands': {
      id: '/global/commands'
      path: '/global/commands'
      fullPath: '/global/commands'
      preLoaderRoute: typeof GlobalCommandsRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/global/agents': {
      id: '/global/agents'
      path: '/global/agents'
      fullPath: '/global/agents'
      preLoaderRoute: typeof GlobalAgentsRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/$projectId/': {
      id: '/projects/$projectId/'
      path: '/'
      fullPath: '/projects/$projectId/'
      preLoaderRoute: typeof ProjectsProjectIdIndexRouteImport
      parentRoute: typeof ProjectsProjectIdRouteRoute
    }
    '/global/skills/': {
      id: '/global/skills/'
      path: '/'
      fullPath: '/global/skills/'
      preLoaderRoute: typeof GlobalSkillsIndexRouteImport
      parentRoute: typeof GlobalSkillsRouteRoute
    }
    '/global/commands/': {
      id: '/global/commands/'
      path: '/'
      fullPath: '/global/commands/'
      preLoaderRoute: typeof GlobalCommandsIndexRouteImport
      parentRoute: typeof GlobalCommandsRouteRoute
    }
    '/global/agents/': {
      id: '/global/agents/'
      path: '/'
      fullPath: '/global/agents/'
      preLoaderRoute: typeof GlobalAgentsIndexRouteImport
      parentRoute: typeof GlobalAgentsRouteRoute
    }
    '/projects/$projectId/settings': {
      id: '/projects/$projectId/settings'
      path: '/settings'
      fullPath: '/projects/$projectId/settings'
      preLoaderRoute: typeof ProjectsProjectIdSettingsRouteImport
      parentRoute: typeof ProjectsProjectIdRouteRoute
    }
    '/global/skills/$skillName': {
      id: '/global/skills/$skillName'
      path: '/$skillName'
      fullPath: '/global/skills/$skillName'
      preLoaderRoute: typeof GlobalSkillsSkillNameRouteImport
      parentRoute: typeof GlobalSkillsRouteRoute
    }
    '/global/agents/$agentName': {
      id: '/global/agents/$agentName'
      path: '/$agentName'
      fullPath: '/global/agents/$agentName'
      preLoaderRoute: typeof GlobalAgentsAgentNameRouteImport
      parentRoute: typeof GlobalAgentsRouteRoute
    }
    '/projects/$projectId/skills': {
      id: '/projects/$projectId/skills'
      path: '/skills'
      fullPath: '/projects/$projectId/skills'
      preLoaderRoute: typeof ProjectsProjectIdSkillsRouteRouteImport
      parentRoute: typeof ProjectsProjectIdRouteRoute
    }
    '/projects/$projectId/commands': {
      id: '/projects/$projectId/commands'
      path: '/commands'
      fullPath: '/projects/$projectId/commands'
      preLoaderRoute: typeof ProjectsProjectIdCommandsRouteRouteImport
      parentRoute: typeof ProjectsProjectIdRouteRoute
    }
    '/projects/$projectId/agents': {
      id: '/projects/$projectId/agents'
      path: '/agents'
      fullPath: '/projects/$projectId/agents'
      preLoaderRoute: typeof ProjectsProjectIdAgentsRouteRouteImport
      parentRoute: typeof ProjectsProjectIdRouteRoute
    }
    '/projects/$projectId/skills/': {
      id: '/projects/$projectId/skills/'
      path: '/'
      fullPath: '/projects/$projectId/skills/'
      preLoaderRoute: typeof ProjectsProjectIdSkillsIndexRouteImport
      parentRoute: typeof ProjectsProjectIdSkillsRouteRoute
    }
    '/projects/$projectId/commands/': {
      id: '/projects/$projectId/commands/'
      path: '/'
      fullPath: '/projects/$projectId/commands/'
      preLoaderRoute: typeof ProjectsProjectIdCommandsIndexRouteImport
      parentRoute: typeof ProjectsProjectIdCommandsRouteRoute
    }
    '/projects/$projectId/agents/': {
      id: '/projects/$projectId/agents/'
      path: '/'
      fullPath: '/projects/$projectId/agents/'
      preLoaderRoute: typeof ProjectsProjectIdAgentsIndexRouteImport
      parentRoute: typeof ProjectsProjectIdAgentsRouteRoute
    }
    '/projects/$projectId/skills/$skillName': {
      id: '/projects/$projectId/skills/$skillName'
      path: '/$skillName'
      fullPath: '/projects/$projectId/skills/$skillName'
      preLoaderRoute: typeof ProjectsProjectIdSkillsSkillNameRouteImport
      parentRoute: typeof ProjectsProjectIdSkillsRouteRoute
    }
    '/projects/$projectId/agents/$agentName': {
      id: '/projects/$projectId/agents/$agentName'
      path: '/$agentName'
      fullPath: '/projects/$projectId/agents/$agentName'
      preLoaderRoute: typeof ProjectsProjectIdAgentsAgentNameRouteImport
      parentRoute: typeof ProjectsProjectIdAgentsRouteRoute
    }
    '/global/commands/$folder/$commandName': {
      id: '/global/commands/$folder/$commandName'
      path: '/$folder/$commandName'
      fullPath: '/global/commands/$folder/$commandName'
      preLoaderRoute: typeof GlobalCommandsFolderCommandNameRouteImport
      parentRoute: typeof GlobalCommandsRouteRoute
    }
    '/projects/$projectId/commands/$folder/$commandName': {
      id: '/projects/$projectId/commands/$folder/$commandName'
      path: '/$folder/$commandName'
      fullPath: '/projects/$projectId/commands/$folder/$commandName'
      preLoaderRoute: typeof ProjectsProjectIdCommandsFolderCommandNameRouteImport
      parentRoute: typeof ProjectsProjectIdCommandsRouteRoute
    }
  }
}

interface GlobalAgentsRouteRouteChildren {
  GlobalAgentsAgentNameRoute: typeof GlobalAgentsAgentNameRoute
  GlobalAgentsIndexRoute: typeof GlobalAgentsIndexRoute
}

const GlobalAgentsRouteRouteChildren: GlobalAgentsRouteRouteChildren = {
  GlobalAgentsAgentNameRoute: GlobalAgentsAgentNameRoute,
  GlobalAgentsIndexRoute: GlobalAgentsIndexRoute,
}

const GlobalAgentsRouteRouteWithChildren =
  GlobalAgentsRouteRoute._addFileChildren(GlobalAgentsRouteRouteChildren)

interface GlobalCommandsRouteRouteChildren {
  GlobalCommandsIndexRoute: typeof GlobalCommandsIndexRoute
  GlobalCommandsFolderCommandNameRoute: typeof GlobalCommandsFolderCommandNameRoute
}

const GlobalCommandsRouteRouteChildren: GlobalCommandsRouteRouteChildren = {
  GlobalCommandsIndexRoute: GlobalCommandsIndexRoute,
  GlobalCommandsFolderCommandNameRoute: GlobalCommandsFolderCommandNameRoute,
}

const GlobalCommandsRouteRouteWithChildren =
  GlobalCommandsRouteRoute._addFileChildren(GlobalCommandsRouteRouteChildren)

interface GlobalSkillsRouteRouteChildren {
  GlobalSkillsSkillNameRoute: typeof GlobalSkillsSkillNameRoute
  GlobalSkillsIndexRoute: typeof GlobalSkillsIndexRoute
}

const GlobalSkillsRouteRouteChildren: GlobalSkillsRouteRouteChildren = {
  GlobalSkillsSkillNameRoute: GlobalSkillsSkillNameRoute,
  GlobalSkillsIndexRoute: GlobalSkillsIndexRoute,
}

const GlobalSkillsRouteRouteWithChildren =
  GlobalSkillsRouteRoute._addFileChildren(GlobalSkillsRouteRouteChildren)

interface ProjectsProjectIdAgentsRouteRouteChildren {
  ProjectsProjectIdAgentsAgentNameRoute: typeof ProjectsProjectIdAgentsAgentNameRoute
  ProjectsProjectIdAgentsIndexRoute: typeof ProjectsProjectIdAgentsIndexRoute
}

const ProjectsProjectIdAgentsRouteRouteChildren: ProjectsProjectIdAgentsRouteRouteChildren =
  {
    ProjectsProjectIdAgentsAgentNameRoute:
      ProjectsProjectIdAgentsAgentNameRoute,
    ProjectsProjectIdAgentsIndexRoute: ProjectsProjectIdAgentsIndexRoute,
  }

const ProjectsProjectIdAgentsRouteRouteWithChildren =
  ProjectsProjectIdAgentsRouteRoute._addFileChildren(
    ProjectsProjectIdAgentsRouteRouteChildren,
  )

interface ProjectsProjectIdCommandsRouteRouteChildren {
  ProjectsProjectIdCommandsIndexRoute: typeof ProjectsProjectIdCommandsIndexRoute
  ProjectsProjectIdCommandsFolderCommandNameRoute: typeof ProjectsProjectIdCommandsFolderCommandNameRoute
}

const ProjectsProjectIdCommandsRouteRouteChildren: ProjectsProjectIdCommandsRouteRouteChildren =
  {
    ProjectsProjectIdCommandsIndexRoute: ProjectsProjectIdCommandsIndexRoute,
    ProjectsProjectIdCommandsFolderCommandNameRoute:
      ProjectsProjectIdCommandsFolderCommandNameRoute,
  }

const ProjectsProjectIdCommandsRouteRouteWithChildren =
  ProjectsProjectIdCommandsRouteRoute._addFileChildren(
    ProjectsProjectIdCommandsRouteRouteChildren,
  )

interface ProjectsProjectIdSkillsRouteRouteChildren {
  ProjectsProjectIdSkillsSkillNameRoute: typeof ProjectsProjectIdSkillsSkillNameRoute
  ProjectsProjectIdSkillsIndexRoute: typeof ProjectsProjectIdSkillsIndexRoute
}

const ProjectsProjectIdSkillsRouteRouteChildren: ProjectsProjectIdSkillsRouteRouteChildren =
  {
    ProjectsProjectIdSkillsSkillNameRoute:
      ProjectsProjectIdSkillsSkillNameRoute,
    ProjectsProjectIdSkillsIndexRoute: ProjectsProjectIdSkillsIndexRoute,
  }

const ProjectsProjectIdSkillsRouteRouteWithChildren =
  ProjectsProjectIdSkillsRouteRoute._addFileChildren(
    ProjectsProjectIdSkillsRouteRouteChildren,
  )

interface ProjectsProjectIdRouteRouteChildren {
  ProjectsProjectIdAgentsRouteRoute: typeof ProjectsProjectIdAgentsRouteRouteWithChildren
  ProjectsProjectIdCommandsRouteRoute: typeof ProjectsProjectIdCommandsRouteRouteWithChildren
  ProjectsProjectIdSkillsRouteRoute: typeof ProjectsProjectIdSkillsRouteRouteWithChildren
  ProjectsProjectIdSettingsRoute: typeof ProjectsProjectIdSettingsRoute
  ProjectsProjectIdIndexRoute: typeof ProjectsProjectIdIndexRoute
}

const ProjectsProjectIdRouteRouteChildren: ProjectsProjectIdRouteRouteChildren =
  {
    ProjectsProjectIdAgentsRouteRoute:
      ProjectsProjectIdAgentsRouteRouteWithChildren,
    ProjectsProjectIdCommandsRouteRoute:
      ProjectsProjectIdCommandsRouteRouteWithChildren,
    ProjectsProjectIdSkillsRouteRoute:
      ProjectsProjectIdSkillsRouteRouteWithChildren,
    ProjectsProjectIdSettingsRoute: ProjectsProjectIdSettingsRoute,
    ProjectsProjectIdIndexRoute: ProjectsProjectIdIndexRoute,
  }

const ProjectsProjectIdRouteRouteWithChildren =
  ProjectsProjectIdRouteRoute._addFileChildren(
    ProjectsProjectIdRouteRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SetupRoute: SetupRoute,
  GlobalAgentsRouteRoute: GlobalAgentsRouteRouteWithChildren,
  GlobalCommandsRouteRoute: GlobalCommandsRouteRouteWithChildren,
  GlobalSkillsRouteRoute: GlobalSkillsRouteRouteWithChildren,
  ProjectsProjectIdRouteRoute: ProjectsProjectIdRouteRouteWithChildren,
  GlobalHooksRoute: GlobalHooksRoute,
  GlobalPluginsRoute: GlobalPluginsRoute,
  GlobalSettingsRoute: GlobalSettingsRoute,
  GlobalIndexRoute: GlobalIndexRoute,
  ProjectsIndexRoute: ProjectsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
